identity:
  author: zhshenyuan
  name: database
  label:
    en_US: Database
  description:
    en_US: This tool is used to execute SQL in an existing database.
    zh_Hans: 此工具用于在已存在的数据库中执行 SQL 查询。
  icon: icon.svg
tools:
  - tools/sql_execute.yaml
  - tools/text2sql.yaml
  - tools/table_schema.yaml
  - tools/csv_query.yaml
extra:
  python:
    source: provider/database.py
credentials_for_provider:
  db_uri:
    help:
      en_US: For example `mysql+pymysql://<user>:<password>@<host>:<port>/<database>`
      zh_Hans: 例如 `mysql+pymysql://<user>:<password>@<host>:<port>/<database>`
    label:
      en_US: Database URI
      zh_Hans: 数据库 URI
    placeholder:
      en_US: Please enter the database URI
      zh_Hans: 请输入数据库 URI
    required: false
    type: secret-input
